# Generated by Django 3.2 on 2021-05-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review_createat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
